#config.yml
recipe: default.v1
assistant_id: duraprotect-bot
language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: RegexEntityExtractor
    use_lookup_tables: true
    use_regexes: true
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 300
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 200
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

policies:
  - name: MemoizationPolicy
    max_history: 6
  - name: RulePolicy
    core_fallback_threshold: 0.3
    enable_fallback_prediction: true
  - name: TEDPolicy
    max_history: 6
    epochs: 250
    constrain_similarities: true
